---

- name: update vm
  gather_facts: false
  hosts: all
  tasks:

    - name: display config
      debug:
      msg: "The hostname is {{ansible_net_hostname}} and the OS is {{ansible_net_version}}

