# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "alpine319"
  config.vm.define "alpine"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "alpine"
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 1]
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end

