Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "control1",
          :box => "debian12",
          :ip => "192.168.56.21",
          :ssh_port => '2201'
        },
        {
          :hostname => "node2",
          :box => "debian12",
          :ip => "192.168.56.22",
          :ssh_port => '2202'
        },
        {
          :hostname => "node3",
          :box => "debian12",
          :ip => "192.168.56.23",
          :ssh_port => '2203'
        },
		{
          :hostname => "node4",
          :box => "debian12",
          :ip => "192.168.56.24",
          :ssh_port => '2204'
        }
      ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", 2048]
                vb.customize ["modifyvm", :id, "--cpus", 1]
            end
        end
    end
end
