---

- hosts: all
  become: yes
  tasks:
    - name: update apt cache and make sure curl, wget, unzip, rsync, git, vim and tmux are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - curl
        - wget
        - unzip
        - rsync
        - git
        - vim
        - tmux

