# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian12"
  config.vm.hostname = "station"
  config.vm.define "station"
  config.vm.network :private_network, ip: "192.168.56.19"
  config.vm.network "forwarded_port", guest: 22, host: 2119, id: "ssh"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "station"
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end

